### ISSUE TITLE
Prevents Mac OS from sleeping

### ISSUE THREAD

**Issue by sumurt** [zenthangplus/franz-zalo#1]
When I run `$ pmset -g assertions` I get the following:

    PreventUserIdleSystemSleep     1
    pid 31560(Franz): [0x000bb46f00018215] 00:03:02 NoIdleSleepAssertion named: "WebRTC has active PeerConnections"

If I disable franz-zalo everything is fine.

**Comment by zenthangplus** [comment]
Hi, franz-zalo just is a plugin which embedded Zalo's app on web, i think this issue related to your machine or franz's core.

**Comment by sumurt** [comment]
It might be related to Zalo's webapp as other services (WhatsApp, Messenger, Hangouts) don't have this issue in Franz, however I lack the skills to identify the issue source. I have just checked and opening Zalo in Chrome leads to the same result, so it's a Zalo (or Chrome) issue, not franz-zalo or Franz.
